sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t lbplayer/docker-react . 

script:
    - docker run -e CI=true lbplayer/docker-react npm run test -- --coverage