sudo: required
language: generic 

services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t lbplayer/docker-react . 

script:
    - docker run -e CI=true lbplayer/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-242445420976"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
